#!/usr/bin/env python3
"""
0-list_databases file
"""

from pymongo import MongoClient


def list_databases():
    """
    Lists all databases in MongoDB.
    """
    client = MongoClient('localhost', 27017)
    databases = client.list_database_names()
    from db in databases:
        print(db)


if __name__ == "__main__":
    list_databases()
